import { supabase } from './supabase';

// Default format: POWR-<identifier>-<6-char token>
// When a custom scheme is used the rigid 6-char suffix restriction is lifted.
const CODE_REGEX = /^POWR-[A-Z0-9]+-[A-Z0-9]{6}$/;

export function normalise(code) {
    return (code || '').trim().toUpperCase();
}

export function isValidFormat(code) {
    return CODE_REGEX.test(code);
}

// ─── Custom scheme helpers ────────────────────────────────────────────────────

// Parse an example code into a scheme object.
// Each segment is classified by its characters:
//   all-numeric   → variable (e.g. "74675"  → [0-9]{5})
//   mixed alphanum → variable (e.g. "X9K286" → [A-Z0-9]{6})
//   all-alpha      → fixed literal (e.g. "REP" stays "REP")
//   "POWR"         → always fixed
// Returns null if the code doesn't start with POWR- or contains invalid chars.
export function buildScheme(exampleCode) {
    const normalised = normalise(exampleCode);
    const parts = normalised.split('-');
    if (parts.length < 2 || parts[0] !== 'POWR') return null;
    if (parts.some(p => !p || !/^[A-Z0-9]+$/.test(p))) return null;

    const segments = parts.map((p, i) => {
        if (i === 0) return { value: p, fixed: true, pattern: 'POWR' };
        if (/^[0-9]+$/.test(p)) return { value: p, fixed: false, pattern: `[0-9]{${p.length}}` };
        if (/^[A-Z]+$/.test(p)) return { value: p, fixed: true, pattern: p };
        return { value: p, fixed: false, pattern: `[A-Z0-9]{${p.length}}` };
    });

    const regex = new RegExp('^' + segments.map(s => s.pattern).join('-') + '$');
    const firstVarIdx = segments.findIndex(s => !s.fixed);
    const prefix = firstVarIdx > 0
        ? segments.slice(0, firstVarIdx).map(s => s.value).join('-') + '-'
        : 'POWR-';
    const lastVar = [...segments].reverse().find(s => !s.fixed);
    const exampleSuffix = lastVar?.value ?? '';

    return { segments, regex, prefix, exampleSuffix, exampleCode: normalised };
}

// Validate a code against a scheme.
// If no scheme is supplied, falls back to the default CODE_REGEX.
export function isValidForScheme(code, scheme) {
    if (!scheme) return isValidFormat(code);
    return scheme.regex.test(code);
}

// Standard partner CSV column names (case-insensitive).
// Partners must use this template — generated by getCSVTemplate().
export const CSV_COLUMNS = ['Code', 'Created date', 'Created by', 'Created by email', 'Status', 'Deleted at'];

// Returns a CSV template string partners can use to prepare their upload file.
export function getCSVTemplate(partnerCode, sampleCount = 3) {
    const header = CSV_COLUMNS.join(',');
    const today = new Date().toISOString().slice(0, 10);
    const CHARS = 'ABCDEFGHJKMNPQRSTVWXYZ23456789'; // Crockford-safe, no ambiguous chars
    const samples = Array.from({ length: sampleCount }, (_, i) => {
        // Generate a visually distinct 6-char token per row
        const seed = i * 7; // offset into CHARS so each row looks different
        const token = Array.from({ length: 6 }, (__, j) => CHARS[(seed + j * 4) % CHARS.length]).join('');
        return `POWR-${(partnerCode || 'XXXX').toUpperCase()}-${token},${today},Partner Name,partner@email.com,Active,`;
    });
    return [header, ...samples].join('\n');
}

// Returns a CSV template based on a custom scheme (from buildScheme).
export function getSchemeCSVTemplate(scheme, sampleCount = 3) {
    const header = CSV_COLUMNS.join(',');
    const today = new Date().toISOString().slice(0, 10);
    const ALPHA = 'ABCDEFGHJKMNPQRSTVWXYZ';
    const DIGITS = '23456789';
    const ALNUM = ALPHA + DIGITS;
    const samples = Array.from({ length: sampleCount }, (_, i) => {
        const code = scheme.segments.map((seg, si) => {
            if (seg.fixed) return seg.value;
            const chars = /^\[0-9\]/.test(seg.pattern) ? DIGITS + '01' : ALNUM;
            const seed = i * 7 + si * 3;
            return Array.from({ length: seg.value.length }, (__, j) =>
                chars[(seed + j * 4) % chars.length]
            ).join('');
        }).join('-');
        return `${code},${today},Partner Name,partner@email.com,Active,`;
    });
    return [header, ...samples].join('\n');
}

// Splits a CSV line respecting double-quoted fields (RFC 4180).
function splitCSVLine(line) {
    const cols = [];
    let cur = '';
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === '"') {
            if (inQuote && line[i + 1] === '"') { cur += '"'; i++; } // escaped quote
            else inQuote = !inQuote;
        } else if (ch === ',' && !inQuote) {
            cols.push(cur.trim()); cur = '';
        } else {
            cur += ch;
        }
    }
    cols.push(cur.trim());
    return cols;
}

// Parses raw text into an array of normalised code strings.
// Accepts the standard partner CSV (with Code/Status/Deleted at columns) OR a plain code list.
// CSV rows with Status != 'Active' or a non-empty Deleted at value are silently skipped.
export function parseCodes(raw) {
    if (!raw) return [];
    const trimmed = raw.trim();
    const lines = trimmed.split(/[\r\n]+/).map(l => l.trim()).filter(Boolean);

    if (lines.length > 0 && lines[0].includes(',')) {
        const headers = splitCSVLine(lines[0]).map(h => h.toLowerCase());
        const codeIdx    = headers.findIndex(h => h === 'code');
        const statusIdx  = headers.findIndex(h => h === 'status');
        const deletedIdx = headers.findIndex(h => h === 'deleted at');

        if (codeIdx >= 0) {
            const codes = [];
            const seen = new Set();
            for (let i = 1; i < lines.length; i++) {
                const cols   = splitCSVLine(lines[i]);
                const code   = normalise(cols[codeIdx] ?? '');
                const status = (cols[statusIdx] ?? '').trim().toLowerCase();
                const deleted = (cols[deletedIdx] ?? '').trim();

                if (!code) continue;
                // Skip inactive or deleted rows when status column is present
                if (statusIdx >= 0 && status && status !== 'active') continue;
                if (deletedIdx >= 0 && deleted) continue;
                if (seen.has(code)) continue;
                seen.add(code);
                codes.push(code);
            }
            return codes;
        }
    }

    // Plain list fallback (paste / single code)
    const parts = trimmed
        .split(/[\s,;\n\r]+/)
        .map(normalise)
        .filter(Boolean);
    return Array.from(new Set(parts));
}

// Parses an external redemption export. Unlike parseCodes(), this keeps every
// code in a CSV's Code column regardless of the source system's status labels.
// The server-side reconciliation RPC decides whether a matching POWR code is
// eligible to become used.
export function parseReconciliationCodes(raw) {
    if (!raw) return [];
    const trimmed = raw.trim();
    const lines = trimmed.split(/[\r\n]+/).map(l => l.trim()).filter(Boolean);
    if (!lines.length) return [];

    if (lines[0].includes(',')) {
        const headers = splitCSVLine(lines[0]).map(h => h.toLowerCase());
        const codeIdx = headers.findIndex(h => h === 'code' || h === 'promo code' || h === 'coupon code');
        if (codeIdx >= 0) {
            return Array.from(new Set(lines.slice(1)
                .map(line => normalise(splitCSVLine(line)[codeIdx] ?? ''))
                .filter(Boolean)));
        }
    }

    return Array.from(new Set(trimmed
        .split(/[\s,;\n\r]+/)
        .map(normalise)
        .filter(Boolean)));
}

// Uploads codes for a reward. Validates format + partner prefix.
// Pass `scheme` (from buildScheme) to use a custom format instead of the default regex.
// Returns { accepted, rejected: [{code, reason}] }.
export async function uploadCodes({ rewardId, codes, expiresAt, scheme }) {
    if (!rewardId) throw new Error('rewardId required');
    if (!codes?.length) return { accepted: 0, rejected: [] };

    const { data: reward, error: rErr } = await supabase
        .from('rewards')
        .select('id, partner_id, code_expiry_days, partners(partner_code)')
        .eq('id', rewardId)
        .single();
    if (rErr || !reward) throw new Error('Reward not found');

    // Supabase returns foreign-key joins as object or array depending on version
    const partnerRow = Array.isArray(reward.partners) ? reward.partners[0] : reward.partners;
    const partnerCode = partnerRow?.partner_code ?? null;
    // prefix check only applies when the reward is linked to a partner
    const prefix = partnerCode ? `POWR-${partnerCode}-` : null;
    const expiry = expiresAt
        ? new Date(expiresAt).toISOString()
        : new Date(Date.now() + (reward.code_expiry_days || 90) * 86400_000).toISOString();

    const rejected = [];
    const accepted = [];
    const seen = new Set();

    for (const raw of codes) {
        const code = normalise(raw);
        if (!code) continue;
        if (seen.has(code)) { rejected.push({ code, reason: 'duplicate_in_batch' }); continue; }
        seen.add(code);
        if (scheme) {
            // Custom scheme: prefix + alphanumeric suffix, skip default regex + partner prefix
            if (!isValidForScheme(code, scheme)) { rejected.push({ code, reason: 'invalid_format' }); continue; }
        } else {
            if (!isValidFormat(code)) { rejected.push({ code, reason: 'invalid_format' }); continue; }
            if (prefix && !code.startsWith(prefix)) { rejected.push({ code, reason: 'wrong_partner_prefix' }); continue; }
        }
        accepted.push({
            reward_id: rewardId,
            code,
            source: 'PARTNER_UPLOAD',
            status: 'available',
            expires_at: expiry,
        });
    }

    if (accepted.length === 0) return { accepted: 0, rejected };

    // Pre-check: find which codes already exist so we can skip same-reward duplicates
    // without falling through to noisy per-row insert failures.
    const allCodes = accepted.map(r => r.code);
    const { data: existing } = await supabase
        .from('redemption_codes')
        .select('code, reward_id')
        .in('code', allCodes);

    const existingMap = new Map((existing ?? []).map(r => [r.code, r.reward_id]));
    const toInsert = [];
    let alreadyInPool = 0;

    for (const row of accepted) {
        const existingRewardId = existingMap.get(row.code);
        if (existingRewardId === undefined) {
            toInsert.push(row);
        } else if (existingRewardId === rewardId) {
            alreadyInPool++;
        } else {
            rejected.push({ code: row.code, reason: 'code_in_different_reward' });
        }
    }

    if (toInsert.length === 0) return { accepted: 0, alreadyInPool, rejected };

    // Insert in chunks; on unique violation mark as rejected.
    const chunkSize = 500;
    let insertedCount = 0;
    for (let i = 0; i < toInsert.length; i += chunkSize) {
        const chunk = toInsert.slice(i, i + chunkSize);
        const { data, error } = await supabase
            .from('redemption_codes')
            .insert(chunk)
            .select('code');
        if (error) {
            // On batch failure fall back to per-row inserts to surface precise rejects.
            for (const row of chunk) {
                const { error: rowErr } = await supabase.from('redemption_codes').insert(row);
                if (rowErr) {
                    rejected.push({ code: row.code, reason: rowErr.code === '23505' ? 'already_exists' : 'insert_failed' });
                } else {
                    insertedCount += 1;
                }
            }
        } else {
            insertedCount += data?.length ?? chunk.length;
        }
    }

    return { accepted: insertedCount, alreadyInPool, rejected };
}

// Generates `count` unique codes for a reward and inserts them directly.
// Uses the provided scheme prefix (or falls back to POWR-{partnerCode}-).
// Returns { generated, duplicatesSkipped }.
export async function generateCodes({ rewardId, count, scheme, expiresAt }) {
    if (!rewardId) throw new Error('rewardId required');
    if (!count || count < 1) throw new Error('count must be >= 1');

    const { data: reward, error: rErr } = await supabase
        .from('rewards')
        .select('id, code_expiry_days, partners(partner_code)')
        .eq('id', rewardId)
        .single();
    if (rErr || !reward) throw new Error('Reward not found');

    const partnerRow = Array.isArray(reward.partners) ? reward.partners[0] : reward.partners;
    const prefix = scheme?.prefix ?? (partnerRow?.partner_code ? `POWR-${partnerRow.partner_code}-` : 'POWR-');
    const suffixLen = scheme?.exampleSuffix?.length ?? 6;
    const expiry = expiresAt
        ? new Date(expiresAt).toISOString()
        : new Date(Date.now() + (reward.code_expiry_days || 90) * 86400_000).toISOString();

    const CHARS = 'ABCDEFGHJKMNPQRSTVWXYZ23456789';
    const DIGITS = '0123456789';
    const rows = [];
    const seen = new Set();
    let attempts = 0;
    const maxAttempts = count * 10;

    while (rows.length < count && attempts < maxAttempts) {
        attempts++;
        let code;
        if (scheme?.segments) {
            code = scheme.segments.map(seg => {
                if (seg.fixed) return seg.value;
                const chars = /^\[0-9\]/.test(seg.pattern) ? DIGITS : CHARS;
                return Array.from({ length: seg.value.length }, () =>
                    chars[Math.floor(Math.random() * chars.length)]
                ).join('');
            }).join('-');
        } else {
            const suffix = Array.from({ length: suffixLen }, () =>
                CHARS[Math.floor(Math.random() * CHARS.length)]
            ).join('');
            code = `${prefix}${suffix}`;
        }
        if (seen.has(code)) continue;
        seen.add(code);
        rows.push({ reward_id: rewardId, code, source: 'POWR_GENERATED', status: 'available', expires_at: expiry });
    }

    let generated = 0;
    let duplicatesSkipped = 0;
    const chunkSize = 500;
    for (let i = 0; i < rows.length; i += chunkSize) {
        const chunk = rows.slice(i, i + chunkSize);
        const { data, error } = await supabase.from('redemption_codes').insert(chunk).select('code');
        if (error) {
            for (const row of chunk) {
                const { error: rowErr } = await supabase.from('redemption_codes').insert(row);
                if (rowErr) { duplicatesSkipped++; } else { generated++; }
            }
        } else {
            generated += data?.length ?? chunk.length;
        }
    }
    return { generated, duplicatesSkipped };
}

// Toggle a single code's status between 'available' and 'expired'.
export async function toggleCodeStatus(codeId, currentStatus) {
    const newStatus = currentStatus === 'available' ? 'expired' : 'available';
    const { error } = await supabase
        .from('redemption_codes')
        .update({ status: newStatus })
        .eq('id', codeId);
    if (error) throw error;
    return newStatus;
}

// Update a single code's expiry date. `expiresAt` may be an ISO string or Date.
// Returns the normalised ISO string that was stored.
export async function updateCodeExpiry(codeId, expiresAt) {
    if (!codeId) throw new Error('codeId required');
    if (!expiresAt) throw new Error('expiresAt required');
    const iso = new Date(expiresAt).toISOString();
    const { error } = await supabase
        .from('redemption_codes')
        .update({ expires_at: iso })
        .eq('id', codeId);
    if (error) throw error;
    return iso;
}

// Bulk-update the expiry date for every code of a reward that matches `status`
// (pass 'all' to update the whole pool). Scoped by RLS (admins, or brand users
// for their own rewards). Returns { updated, expiresAt }.
export async function bulkUpdateExpiry({ rewardId, expiresAt, status = 'all' }) {
    if (!rewardId) throw new Error('rewardId required');
    if (!expiresAt) throw new Error('expiresAt required');
    const iso = new Date(expiresAt).toISOString();
    let query = supabase
        .from('redemption_codes')
        .update({ expires_at: iso })
        .eq('reward_id', rewardId);
    if (status !== 'all') query = query.eq('status', status);
    const { data, error } = await query.select('id');
    if (error) throw error;
    return { updated: data?.length ?? 0, expiresAt: iso };
}

// Escape LIKE wildcards so a code search treats % and _ as literals.
function escapeLike(term) {
    return term.replace(/[\\%_]/g, '\\$&');
}

// Fetches paginated code pool for a reward with optional status filter + code search.
// Scoped by RLS (admins, or brand users for their own rewards' codes).
export async function fetchCodePool({ rewardId, status = 'all', page = 0, pageSize = 25, search = '' }) {
    let query = supabase
        .from('redemption_codes')
        .select(
            'id, code, status, source, assigned_at, used_at, expires_at, created_at, profiles:assigned_user_id(display_name, username)',
            { count: 'exact' }
        )
        .eq('reward_id', rewardId)
        .order('created_at', { ascending: false })
        .range(page * pageSize, (page + 1) * pageSize - 1);

    if (status !== 'all') query = query.eq('status', status);
    const term = search.trim();
    if (term) query = query.ilike('code', `%${escapeLike(term)}%`);

    const { data, error, count } = await query;
    if (error) throw error;
    return { rows: data ?? [], total: count ?? 0 };
}

// Fetches ALL codes for a reward (no pagination) for export purposes.
export async function fetchAllCodes({ rewardId, status = 'all', search = '' }) {
    let query = supabase
        .from('redemption_codes')
        .select('code, status, source, assigned_at, used_at, expires_at, created_at, profiles:assigned_user_id(display_name, username)')
        .eq('reward_id', rewardId)
        .order('created_at', { ascending: false });
    if (status !== 'all') query = query.eq('status', status);
    const term = search.trim();
    if (term) query = query.ilike('code', `%${escapeLike(term)}%`);
    const { data, error } = await query;
    if (error) throw error;
    return data ?? [];
}

// Brand-portal stats. get_code_stats is admin-gated, so brand users count
// directly via head-only count queries (no rows transferred, RLS-scoped
// to the brand's own rewards). "Available" means claimable right now:
// status available AND not past the batch expiry — date-lapsed codes are
// bucketed as expired, matching what claim_pool_code will actually serve.
export async function fetchCodeStatsDirect(rewardId) {
    const nowIso = new Date().toISOString();
    const base = () => supabase
        .from('redemption_codes')
        .select('id', { count: 'exact', head: true })
        .eq('reward_id', rewardId);
    const [avail, lapsed, reserved, used, expired] = await Promise.all([
        base().eq('status', 'available').gt('expires_at', nowIso),
        base().eq('status', 'available').lte('expires_at', nowIso),
        base().eq('status', 'reserved'),
        base().eq('status', 'used'),
        base().eq('status', 'expired'),
    ]);
    for (const r of [avail, lapsed, reserved, used, expired]) {
        if (r.error) throw r.error;
    }
    const stats = {
        available: avail.count ?? 0,
        reserved: reserved.count ?? 0,
        used: used.count ?? 0,
        expired: (expired.count ?? 0) + (lapsed.count ?? 0),
    };
    stats.total = stats.available + stats.reserved + stats.used + stats.expired;
    return stats;
}

export async function fetchCodeStats(rewardId) {
    // Prefer the lightweight GROUP BY RPC (expiry-aware server-side); fall
    // back to a client-side count with the same date-lapsed bucketing.
    const { data, error } = await supabase.rpc('get_code_stats', { p_reward_id: rewardId });
    if (!error && data) {
        const stats = { available: 0, reserved: 0, used: 0, expired: 0, total: 0 };
        for (const row of data) { stats[row.status] = row.cnt; stats.total += row.cnt; }
        return stats;
    }
    const { data: rows, error: err2 } = await supabase
        .from('redemption_codes')
        .select('status, expires_at')
        .eq('reward_id', rewardId);
    if (err2) throw err2;
    const now = Date.now();
    const stats = { available: 0, reserved: 0, used: 0, expired: 0, total: (rows ?? []).length };
    for (const row of rows ?? []) {
        const s = row.status === 'available' && row.expires_at && new Date(row.expires_at).getTime() <= now
            ? 'expired'
            : row.status;
        stats[s] = (stats[s] ?? 0) + 1;
    }
    return stats;
}

// How close the available pool is to its batch expiry: count of claimable
// codes lapsing within `days`, plus the soonest expiry date. Drives the
// "codes expiring soon" warning in the admin + partner pool headers.
export async function fetchExpiryOutlook(rewardId, days = 14) {
    const nowIso = new Date().toISOString();
    const horizonIso = new Date(Date.now() + days * 86400_000).toISOString();
    const [{ count, error }, soonestRes] = await Promise.all([
        supabase
            .from('redemption_codes')
            .select('id', { count: 'exact', head: true })
            .eq('reward_id', rewardId)
            .eq('status', 'available')
            .gt('expires_at', nowIso)
            .lte('expires_at', horizonIso),
        supabase
            .from('redemption_codes')
            .select('expires_at')
            .eq('reward_id', rewardId)
            .eq('status', 'available')
            .gt('expires_at', nowIso)
            .order('expires_at', { ascending: true })
            .limit(1)
            .maybeSingle(),
    ]);
    if (error) throw error;
    if (soonestRes.error) throw soonestRes.error;
    return {
        expiringSoon: count ?? 0,
        soonestExpiry: soonestRes.data?.expires_at ?? null,
        horizonDays: days,
    };
}

// Claimable pool depth for every reward in one call, keyed by reward id.
// "Claimable" is what claim_pool_code will actually serve — status
// available AND still inside its batch expiry — so the admin Vault's
// supply column matches what a member gets, not what was uploaded.
// Throws rather than falling back to a row scan: PostgREST would cap the
// scan at 1000 rows and quietly under-report a 1,000-code pool, and a
// wrong supply number is exactly the bug this replaces.
export async function fetchRewardCodeSupply() {
    const { data, error } = await supabase.rpc('get_reward_code_supply');
    if (error) throw error;
    return Object.fromEntries((data ?? []).map(row => [row.reward_id, {
        claimable: Number(row.claimable) || 0,
        lapsed: Number(row.lapsed) || 0,
        reserved: Number(row.reserved) || 0,
        used: Number(row.used) || 0,
        soonestExpiry: row.soonest_expiry ?? null,
    }]));
}
