import { supabase } from './supabase';

// Format: POWR-<identifier>-<6-char token>
// The middle identifier can be any length (1+ chars) — e.g. TRIBE, BULK, GYM
const CODE_REGEX = /^POWR-[A-Z0-9]+-[A-Z0-9]{6}$/;

export function normalise(code) {
    return (code || '').trim().toUpperCase();
}

export function isValidFormat(code) {
    return CODE_REGEX.test(code);
}

// Standard partner CSV column names (case-insensitive).
// Partners must use this template — generated by getCSVTemplate().
export const CSV_COLUMNS = ['Code', 'Created date', 'Created by', 'Created by email', 'Status', 'Deleted at'];

// Returns a CSV template string partners can use to prepare their upload file.
export function getCSVTemplate(partnerCode, sampleCount = 3) {
    const header = CSV_COLUMNS.join(',');
    const today = new Date().toISOString().slice(0, 10);
    const CHARS = 'ABCDEFGHJKMNPQRSTVWXYZ23456789'; // Crockford-safe, no ambiguous chars
    const samples = Array.from({ length: sampleCount }, (_, i) => {
        // Generate a visually distinct 6-char token per row
        const seed = i * 7; // offset into CHARS so each row looks different
        const token = Array.from({ length: 6 }, (__, j) => CHARS[(seed + j * 4) % CHARS.length]).join('');
        return `POWR-${(partnerCode || 'XXXX').toUpperCase()}-${token},${today},Partner Name,partner@email.com,Active,`;
    });
    return [header, ...samples].join('\n');
}

// Splits a CSV line respecting double-quoted fields (RFC 4180).
function splitCSVLine(line) {
    const cols = [];
    let cur = '';
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === '"') {
            if (inQuote && line[i + 1] === '"') { cur += '"'; i++; } // escaped quote
            else inQuote = !inQuote;
        } else if (ch === ',' && !inQuote) {
            cols.push(cur.trim()); cur = '';
        } else {
            cur += ch;
        }
    }
    cols.push(cur.trim());
    return cols;
}

// Parses raw text into an array of normalised code strings.
// Accepts the standard partner CSV (with Code/Status/Deleted at columns) OR a plain code list.
// CSV rows with Status != 'Active' or a non-empty Deleted at value are silently skipped.
export function parseCodes(raw) {
    if (!raw) return [];
    const trimmed = raw.trim();
    const lines = trimmed.split(/[\r\n]+/).map(l => l.trim()).filter(Boolean);

    if (lines.length > 0 && lines[0].includes(',')) {
        const headers = splitCSVLine(lines[0]).map(h => h.toLowerCase());
        const codeIdx    = headers.findIndex(h => h === 'code');
        const statusIdx  = headers.findIndex(h => h === 'status');
        const deletedIdx = headers.findIndex(h => h === 'deleted at');

        if (codeIdx >= 0) {
            const codes = [];
            const seen = new Set();
            for (let i = 1; i < lines.length; i++) {
                const cols   = splitCSVLine(lines[i]);
                const code   = normalise(cols[codeIdx] ?? '');
                const status = (cols[statusIdx] ?? '').trim().toLowerCase();
                const deleted = (cols[deletedIdx] ?? '').trim();

                if (!code) continue;
                // Skip inactive or deleted rows when status column is present
                if (statusIdx >= 0 && status && status !== 'active') continue;
                if (deletedIdx >= 0 && deleted) continue;
                if (seen.has(code)) continue;
                seen.add(code);
                codes.push(code);
            }
            return codes;
        }
    }

    // Plain list fallback (paste / single code)
    const parts = trimmed
        .split(/[\s,;\n\r]+/)
        .map(normalise)
        .filter(Boolean);
    return Array.from(new Set(parts));
}

// Uploads codes for a reward. Validates format + partner prefix.
// Returns { accepted, rejected: [{code, reason}] }.
export async function uploadCodes({ rewardId, codes, expiresAt }) {
    if (!rewardId) throw new Error('rewardId required');
    if (!codes?.length) return { accepted: 0, rejected: [] };

    const { data: reward, error: rErr } = await supabase
        .from('rewards')
        .select('id, partner_id, code_expiry_days, partners(partner_code)')
        .eq('id', rewardId)
        .single();
    if (rErr || !reward) throw new Error('Reward not found');

    // Supabase returns foreign-key joins as object or array depending on version
    const partnerRow = Array.isArray(reward.partners) ? reward.partners[0] : reward.partners;
    const partnerCode = partnerRow?.partner_code ?? null;
    // prefix check only applies when the reward is linked to a partner
    const prefix = partnerCode ? `POWR-${partnerCode}-` : null;
    const expiry = expiresAt
        ? new Date(expiresAt).toISOString()
        : new Date(Date.now() + (reward.code_expiry_days || 90) * 86400_000).toISOString();

    const rejected = [];
    const accepted = [];
    const seen = new Set();

    for (const raw of codes) {
        const code = normalise(raw);
        if (!code) continue;
        if (seen.has(code)) { rejected.push({ code, reason: 'duplicate_in_batch' }); continue; }
        seen.add(code);
        if (!isValidFormat(code)) { rejected.push({ code, reason: 'invalid_format' }); continue; }
        if (prefix && !code.startsWith(prefix)) { rejected.push({ code, reason: 'wrong_partner_prefix' }); continue; }
        accepted.push({
            reward_id: rewardId,
            code,
            source: 'PARTNER_UPLOAD',
            status: 'available',
            expires_at: expiry,
        });
    }

    if (accepted.length === 0) return { accepted: 0, rejected };

    // Insert in chunks; on unique violation mark as rejected.
    const chunkSize = 500;
    let insertedCount = 0;
    for (let i = 0; i < accepted.length; i += chunkSize) {
        const chunk = accepted.slice(i, i + chunkSize);
        const { data, error } = await supabase
            .from('redemption_codes')
            .insert(chunk)
            .select('code');
        if (error) {
            // On batch failure fall back to per-row inserts to surface precise rejects.
            for (const row of chunk) {
                const { error: rowErr } = await supabase.from('redemption_codes').insert(row);
                if (rowErr) {
                    rejected.push({ code: row.code, reason: rowErr.code === '23505' ? 'already_exists' : 'insert_failed' });
                } else {
                    insertedCount += 1;
                }
            }
        } else {
            insertedCount += data?.length ?? chunk.length;
        }
    }

    return { accepted: insertedCount, rejected };
}

// Fetches paginated code pool for a reward with optional status filter.
// Requires the calling user to be an admin (RLS policy on redemption_codes).
export async function fetchCodePool({ rewardId, status = 'all', page = 0, pageSize = 25 }) {
    let query = supabase
        .from('redemption_codes')
        .select(
            'id, code, status, source, assigned_at, used_at, expires_at, created_at, profiles:assigned_user_id(display_name, username)',
            { count: 'exact' }
        )
        .eq('reward_id', rewardId)
        .order('created_at', { ascending: false })
        .range(page * pageSize, (page + 1) * pageSize - 1);

    if (status !== 'all') query = query.eq('status', status);

    const { data, error, count } = await query;
    if (error) throw error;
    return { rows: data ?? [], total: count ?? 0 };
}

export async function fetchCodeStats(rewardId) {
    // Prefer the lightweight GROUP BY RPC; fall back to client-side count
    const { data, error } = await supabase.rpc('get_code_stats', { p_reward_id: rewardId });
    if (!error && data) {
        const stats = { available: 0, reserved: 0, used: 0, expired: 0, total: 0 };
        for (const row of data) { stats[row.status] = row.cnt; stats.total += row.cnt; }
        return stats;
    }
    const { data: rows, error: err2 } = await supabase
        .from('redemption_codes')
        .select('status')
        .eq('reward_id', rewardId);
    if (err2) throw err2;
    const stats = { available: 0, reserved: 0, used: 0, expired: 0, total: (rows ?? []).length };
    for (const row of rows ?? []) stats[row.status] = (stats[row.status] ?? 0) + 1;
    return stats;
}
