import React from 'react';
import { Callout, CodeBlock, DocsLayout, NextUp, P, Section, Step, Steps, Table } from './docsShared';

// /docs/promo-codes — the manual method, documented for someone who has never
// touched an API. Mirrors the portal's Promo Codes workspace step for step.

const TOC = [
    ['before', 'Before you start'],
    ['setup', 'Setting up in four steps'],
    ['format', 'Code format'],
    ['generate', 'Letting POWR generate'],
    ['upload', 'Uploading your own codes'],
    ['rejected', 'Why codes get rejected'],
    ['member', 'What the member gets'],
    ['reconcile', 'Marking codes as used'],
    ['manage', 'Managing the pool'],
    ['topup', 'Keeping it stocked'],
    ['troubleshoot', 'Troubleshooting'],
];

export default function DocsPromoCodes() {
    return (
        <DocsLayout
            eyebrow="Guide · Promo Codes"
            title="Promo codes, straight from the portal"
            intro="The no-engineering method. You keep a pool of codes for each reward — either uploaded from your own system or generated by POWR — and we hand one to each member who redeems. Nothing to host, nothing to integrate, and you can be live in about five minutes."
            toc={TOC}
        >
            <Section id="before" title="Before you start">
                <P>You need two things:</P>
                <P>
                    <b>1. A digital reward set to “unique code”.</b> Create it under <b>My Rewards</b>. On the
                    delivery step choose <b>Unique code</b> and set your <b>code name</b> — the short brand
                    segment that sits in the middle of every code you issue. Rewards set to a shared affiliate
                    link, and physical rewards, never have a code pool and won’t appear in this workspace.
                </P>
                <P>
                    <b>2. Promo Codes as your delivery method.</b> Portal → <b>Integration</b> → choose{' '}
                    <b>Promo Codes</b>. It then lives permanently in your sidebar. (If you’re on Shopify or the
                    API, you can still open this workspace — your codes there act as a fallback buffer rather
                    than the main supply.)
                </P>
                <Callout tone="note" title="Set the reward up first, go live second">
                    A reward doesn’t have to be live in the app to have its pool loaded. Load codes first, flip
                    the reward live second, and no member ever meets a reward with an empty pool.
                </Callout>
            </Section>

            <Section id="setup" title="Setting up in four steps">
                <Steps>
                    <Step n="1" title="Pick the reward">
                        Open <b>Promo Codes</b> and choose a reward from the dropdown. Each reward keeps its own
                        separate pool — codes never spill between them. The green count next to each name is how
                        many codes are currently available to claim.
                    </Step>
                    <Step n="2" title="Set the code format (optional)">
                        Switch to the <b>Add codes</b> tab. In <b>Code format</b>, type one example of a code you
                        want to issue — say <code className="font-mono">POWR-TRIBE-A1B2C3</code>. POWR reads the
                        shape and applies it to everything you generate or upload for this reward. Leave it blank
                        to use the default. See <a href="#format" className="underline font-bold text-[#8a7600]">Code format</a> for the rules.
                    </Step>
                    <Step n="3" title="Add the codes">
                        Either hit <b>Generate Batch</b> and let POWR create them, or paste/upload the codes your
                        own system already issued. Both land in the same pool and behave identically from there.
                    </Step>
                    <Step n="4" title="Check it reads as live">
                        The progress strip at the top of the page should show all three stages complete, and the
                        <b> Code Pool</b> header should show a non-zero <b>avail</b> count. If the reward is live
                        in the app, you’re done — members start drawing from the pool immediately.
                    </Step>
                </Steps>
            </Section>

            <Section id="format" title="Code format">
                <P>
                    Codes in POWR follow a house shape so members recognise them and support can spot them
                    instantly. The default is:
                </P>
                <CodeBlock>{`POWR-<YOUR CODE NAME>-<6 characters>

POWR-TRIBE-8FK2QN
POWR-TRIBE-VW3H7P`}</CodeBlock>
                <P>
                    You can define your own shape instead by typing a single example into <b>Code format</b>.
                    POWR splits it on hyphens and classifies each segment by what’s in it:
                </P>
                <Table
                    head={['Segment in your example', 'Read as', 'Effect']}
                    rows={[
                        ['POWR', 'Fixed', 'Always required as the first segment'],
                        ['Letters only — TRIBE', 'Fixed', 'Appears verbatim in every code'],
                        ['Digits only — 74675', 'Variable', 'Replaced with 5 random digits'],
                        ['Mixed — X9K286', 'Variable', 'Replaced with 6 random letters/digits, same length'],
                    ]}
                />
                <P>
                    The portal shows you the parse live — gold chips are fixed, green chips are variable — so you
                    can see exactly what you’ve described before you generate anything. Two rules always hold:
                    the first segment must be <code className="font-mono">POWR</code>, and codes may only contain
                    A–Z, 0–9 and hyphens. Codes are case-insensitive and stored uppercase.
                </P>
                <Callout tone="note" title="The format is a per-browser hint">
                    Your example code is remembered per reward in the browser you typed it in — it isn’t a
                    setting saved on the reward. If a colleague loads codes from their own laptop, or you switch
                    machines, re-enter the same example first so the batch comes out consistent.
                </Callout>
            </Section>

            <Section id="generate" title="Letting POWR generate">
                <P>
                    The fastest path, and the right one if your discount is enforced by a rule rather than by a
                    specific code string — for example a promotion you’ll apply manually at the till, or a code
                    list you’re happy to accept as-is.
                </P>
                <P>
                    Set a count (1–5,000 per batch) and hit <b>Generate Batch</b>. POWR builds each code from your
                    format, checking uniqueness as it goes. Duplicates are skipped silently and reported in the
                    result — generate 500 and you may see “498 generated · 2 skipped”, which is normal.
                </P>
                <P>
                    The random characters come from a deliberately reduced alphabet:{' '}
                    <code className="font-mono">ABCDEFGHJKMNPQRSTVWXYZ23456789</code>. I, L, O, U, 0 and 1 are
                    excluded so nobody mistypes a code they’re reading off a phone screen.
                </P>
                <Callout tone="warn" title="Generated codes are not known to your store">
                    POWR doesn’t create anything in your e-commerce system — it only records the strings.
                    Whatever you generate here, your checkout has to be able to accept. Export the batch (see{' '}
                    <a href="#manage" className="underline font-bold">Managing the pool</a>) and load it into your
                    store’s discount list, or use <a href="#upload" className="underline font-bold">upload</a> instead
                    and let your store be the source of truth.
                </Callout>
            </Section>

            <Section id="upload" title="Uploading your own codes">
                <P>
                    If your store already issues the codes, bring them here. In the <b>Add codes</b> tab you have
                    three ways in, all equivalent:
                </P>
                <P>
                    <b>One at a time</b> — type it in the single-code field and hit <b>Add</b>. Handy for
                    testing, or for topping up by a handful.
                </P>
                <P>
                    <b>Paste a list</b> — drop codes into the big box, separated by new lines, commas, semicolons
                    or spaces. The counter under the box tells you how many were detected before you commit.
                </P>
                <P>
                    <b>Upload a CSV</b> — hit <b>Upload CSV</b> to load a file into the box, then upload the
                    batch. Hit <b>Template</b> first to download a correctly-shaped file, pre-filled with sample
                    codes in your chosen format:
                </P>
                <CodeBlock title="POWR-codes-template.csv">{`Code,Created date,Created by,Created by email,Status,Deleted at
POWR-TRIBE-AEJPTX,2026-07-20,Partner Name,partner@email.com,Active,
POWR-TRIBE-HMRWBF,2026-07-20,Partner Name,partner@email.com,Active,
POWR-TRIBE-PVAFKQ,2026-07-20,Partner Name,partner@email.com,Active,`}</CodeBlock>
                <P>Only three columns actually mean anything, and the header names are matched case-insensitively:</P>
                <Table
                    head={['Column', 'What we do with it']}
                    rows={[
                        ['Code', 'Required. The code itself. Everything else is optional.'],
                        ['Status', 'If present and not “Active”, the row is skipped — so you can export your store’s full code list without filtering it first.'],
                        ['Deleted at', 'If present and non-empty, the row is skipped. Same reason.'],
                    ]}
                />
                <P>
                    Any other columns are ignored, and duplicate rows within one file are collapsed. If a file
                    has no <code className="font-mono">Code</code> header at all, we fall back to treating the
                    whole thing as a plain list.
                </P>
            </Section>

            <Section id="rejected" title="Why codes get rejected">
                <P>
                    Every upload reports back <b>added · already in pool · rejected</b>. “Already in pool” is
                    harmless — re-uploading the same file is safe and won’t duplicate anything. Rejections are
                    listed in your browser console with a reason each; here’s what they mean:
                </P>
                <Table
                    head={['Reason', 'What happened', 'Fix']}
                    rows={[
                        ['invalid_format', 'The code doesn’t match the format for this reward.', 'Check the Code format box matches the codes you’re pasting — an example code entered there changes what counts as valid.'],
                        ['wrong_partner_prefix', 'The reward is tied to a POWR partner code, and this code doesn’t start with it.', 'Use POWR-<your code name>- as the prefix, or define a custom format for the reward.'],
                        ['duplicate_in_batch', 'The same code appeared twice in what you pasted.', 'Nothing to do — the first copy was accepted.'],
                        ['code_in_different_reward', 'That exact code already exists on another reward.', 'Codes are globally unique in POWR. Issue a distinct code, or remove it from the other reward’s pool first.'],
                        ['already_exists', 'The code was created between your paste and the upload finishing.', 'Re-run the upload; it will report it as already in pool.'],
                    ]}
                />
                <Callout tone="note" title="A rejected batch is never half-applied in a confusing way">
                    Good codes are accepted and bad ones are reported — you never have to work out which half
                    landed. Fix the rejects and upload again; the accepted ones will just come back as “already
                    in pool”.
                </Callout>
            </Section>

            <Section id="member" title="What the member gets">
                <P>
                    When a member redeems, we take the <b>oldest still-valid available code</b> in that reward’s
                    pool, mark it <code className="font-mono">reserved</code>, and place it in their wallet with
                    a fresh expiry. That’s an atomic claim — two members redeeming at the same instant can never
                    be handed the same code.
                </P>
                <P>
                    From your side nothing needs to happen at that moment. The code shows up as{' '}
                    <code className="font-mono">reserved</code> in the ledger and under <b>Redemptions</b> in the
                    portal, and it’s now the member’s to spend at your checkout.
                </P>
                <P>
                    If the pool is empty (or every remaining code has expired) the redemption fails and the
                    member keeps their POWR — see <a href="#topup" className="underline font-bold text-[#8a7600]">Keeping it stocked</a>.
                </P>
            </Section>

            <Section id="reconcile" title="Marking codes as used">
                <P>
                    Reconciliation is how you tell POWR which codes were actually spent. It’s optional — nothing
                    breaks if you skip it — but it’s what makes your redemption reporting reflect real revenue
                    rather than intent, and it’s the only way to tell a claimed-and-spent code from a
                    claimed-and-forgotten one.
                </P>
                <P>
                    Export the redeemed codes from your store, open the <b>Reconcile</b> tab, then paste the list
                    or import the CSV. We accept a <code className="font-mono">Code</code>,{' '}
                    <code className="font-mono">Promo code</code> or <code className="font-mono">Coupon code</code>{' '}
                    column, or a plain list — and unlike uploading, we ignore your store’s status labels
                    completely here. Up to 5,000 codes per run.
                </P>
                <P>The result tells you exactly what moved:</P>
                <Table
                    head={['Result', 'Meaning']}
                    rows={[
                        ['marked used', 'Codes that were in a member’s wallet and are now confirmed spent.'],
                        ['already reconciled', 'You’d already told us about these. Harmless — re-submitting the same export is safe.'],
                        ['not assigned', 'The code exists on this reward but no member ever claimed it. Usually means it was spent by someone outside POWR.'],
                        ['not in this pool', 'We don’t have that code on this reward — check you picked the right reward, or that the export isn’t from a different campaign.'],
                    ]}
                />
                <Callout tone="warn" title="Reconciliation only goes one way">
                    It can move a code from <code className="font-mono">reserved</code> to{' '}
                    <code className="font-mono">used</code> and nothing else. There’s no way to release a code
                    back to the pool or reassign it to someone else — once a member holds a code, it’s theirs.
                </Callout>
            </Section>

            <Section id="manage" title="Managing the pool">
                <P>
                    The <b>Manage pool</b> tab is the full ledger for the selected reward: every code, its state,
                    when it was claimed, when it was used, when it expires.
                </P>
                <P>
                    <b>Filter and search.</b> The status chips narrow to available / reserved / used / expired,
                    and the search box matches any part of a code — useful when a member emails you asking about
                    one specific code.
                </P>
                <P>
                    <b>Pull a code out of circulation.</b> The toggle on the right of each row flips an{' '}
                    <code className="font-mono">available</code> code to <code className="font-mono">expired</code>{' '}
                    so it can never be claimed, and back again. It only appears on unclaimed codes — you can’t
                    retract a code a member already holds.
                </P>
                <P>
                    <b>Export.</b> <b>CSV</b> and <b>Excel</b> download whatever your current filter and search
                    are showing, with claimed / used / expiry dates. Filter to <b>available</b> and export if you
                    need to load a generated batch into your own store.
                </P>
            </Section>

            <Section id="topup" title="Keeping it stocked">
                <P>
                    An empty pool means failed redemptions, so this is the one bit of ongoing upkeep the manual
                    method asks of you. Two things to watch:
                </P>
                <P>
                    <b>The available count.</b> It’s on the reward dropdown, on the Code Pool header, and the
                    portal Overview raises an alert on any live reward whose available count has hit zero. Treat
                    that alert as urgent — members are being turned away while it’s showing.
                </P>
                <P>
                    <b>Expiry drift.</b> Codes are stamped with the reward’s code lifetime when you load them,
                    counted from the upload — not from when a member claims them. A pool loaded a year ago can
                    read “available” while being entirely unclaimable. Sort by the <b>Expires</b> column now and
                    then, and prefer loading a few sensible batches over one enormous one.
                </P>
                <Callout tone="note" title="Rough sizing">
                    Load enough for a few weeks of expected redemptions rather than a year of them. Topping up
                    takes under a minute, and small batches keep expiry problems from ever arising.
                </Callout>
            </Section>

            <Section id="troubleshoot" title="Troubleshooting">
                <P>
                    <b>My reward isn’t in the dropdown.</b> Only digital rewards set to “unique code” have pools.
                    Check the reward’s delivery setting under My Rewards — affiliate-link and physical rewards
                    are excluded by design.
                </P>
                <P>
                    <b>Everything I paste is rejected as invalid_format.</b> Almost always the Code format box.
                    Either it holds an example that doesn’t match what you’re pasting, or it’s empty and your
                    codes don’t fit the default <code className="font-mono">POWR-XXXX-XXXXXX</code> shape. Clear
                    it, or set it to one real code from your batch.
                </P>
                <P>
                    <b>The count says available but members can’t redeem.</b> Check the reward is live in the
                    app, that any stock limit on the reward hasn’t been reached, and that the codes haven’t
                    expired in the pool.
                </P>
                <P>
                    <b>A member says their code was rejected at checkout.</b> Confirm the code exists in your own
                    store. Codes generated by POWR are only strings until you load them into your system — see
                    the warning under <a href="#generate" className="underline font-bold text-[#8a7600]">Letting POWR generate</a>.
                </P>
                <P>
                    <b>I need to cancel a batch I just loaded.</b> Filter to <b>available</b> and toggle the rows
                    to expired. Anything already claimed stays with its member.
                </P>
            </Section>

            <NextUp
                to="/docs/shopify"
                label="Running a Shopify store?"
                detail="Skip the uploads entirely — connect once and every redemption mints its own single-use code."
            />
        </DocsLayout>
    );
}
