-- Tracker sprints: a fixed stretch of work the team commits to, planned from
-- the backlog, run on the board, closed with a summary.
--
-- Done inside a sprint means what it means everywhere in the Tracker:
-- VERIFIED (or closed as done). Something live but unproven isn't done — it
-- carries over, because the proof is still owed.
--
-- One sprint runs at a time. Starting one snapshots what was committed;
-- completing one freezes the numbers (committed, added mid-sprint, done,
-- dropped, still live, points) and moves everything unfinished into the next
-- sprint or back to the backlog, in one transaction.

create table if not exists public.tracker_sprints (
    id uuid primary key default gen_random_uuid(),
    number integer generated by default as identity unique,
    name text not null check (length(btrim(name)) between 1 and 80),
    goal text check (length(goal) <= 500),
    starts_on date not null,
    ends_on date not null,
    status text not null default 'planned' check (status in ('planned', 'active', 'completed')),
    -- What was in the sprint the moment it started — the commitment.
    committed_ids uuid[] not null default '{}',
    -- Frozen when it completes (see tracker_complete_sprint).
    summary jsonb,
    started_at timestamptz,
    completed_at timestamptz,
    created_by uuid default auth.uid() references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (ends_on >= starts_on)
);

create unique index if not exists tracker_sprints_one_active on public.tracker_sprints ((true)) where status = 'active';

alter table public.tracker_issues
    add column if not exists sprint_id uuid references public.tracker_sprints(id) on delete set null;

create index if not exists tracker_issues_sprint_idx on public.tracker_issues (sprint_id) where sprint_id is not null;

create or replace function public.tracker_sprints_touch()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists tracker_sprints_touch on public.tracker_sprints;
create trigger tracker_sprints_touch before update on public.tracker_sprints
    for each row execute function public.tracker_sprints_touch();

-- History: "moved it into Sprint 4" / "took it out of the sprint".
create or replace function public.tracker_issues_sprint_history()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.sprint_id is distinct from old.sprint_id then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, coalesce(auth.uid(), new.updated_by), 'sprint', old.sprint_id::text, new.sprint_id::text);
    end if;
    return new;
end;
$$;

drop trigger if exists tracker_issues_sprint_history on public.tracker_issues;
create trigger tracker_issues_sprint_history after update of sprint_id on public.tracker_issues
    for each row execute function public.tracker_issues_sprint_history();

-- Effort sizes as points (XS 1, S 2, M 3, L 5, XL 8; unsized 0). The admin
-- page uses the same scale (tracker/model.js EFFORT_POINTS).
create or replace function public.tracker_effort_points(p_effort text)
returns integer
language sql
immutable
as $$
    select case p_effort when 'xs' then 1 when 's' then 2 when 'm' then 3 when 'l' then 5 when 'xl' then 8 else 0 end;
$$;

create or replace function public.tracker_start_sprint(p_sprint uuid)
returns public.tracker_sprints
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_sprint public.tracker_sprints;
    v_running public.tracker_sprints;
begin
    if not public.is_admin() then
        raise exception 'Admins only';
    end if;
    select * into v_sprint from public.tracker_sprints where id = p_sprint for update;
    if not found then
        raise exception 'That sprint no longer exists';
    end if;
    if v_sprint.status <> 'planned' then
        raise exception '% has already started', v_sprint.name;
    end if;
    select * into v_running from public.tracker_sprints where status = 'active';
    if found then
        raise exception '% is still running — complete it first', v_running.name;
    end if;

    update public.tracker_sprints
       set status = 'active',
           started_at = now(),
           committed_ids = coalesce((select array_agg(id) from public.tracker_issues where sprint_id = p_sprint), '{}')
     where id = p_sprint
     returning * into v_sprint;
    return v_sprint;
end;
$$;

create or replace function public.tracker_complete_sprint(p_sprint uuid, p_carry_to uuid default null)
returns public.tracker_sprints
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_sprint public.tracker_sprints;
    v_target public.tracker_sprints;
    v_summary jsonb;
    v_carried uuid[];
begin
    if not public.is_admin() then
        raise exception 'Admins only';
    end if;
    select * into v_sprint from public.tracker_sprints where id = p_sprint for update;
    if not found then
        raise exception 'That sprint no longer exists';
    end if;
    if v_sprint.status <> 'active' then
        raise exception '% isn''t running', v_sprint.name;
    end if;
    if p_carry_to is not null then
        select * into v_target from public.tracker_sprints where id = p_carry_to;
        if not found or v_target.status = 'completed' or v_target.id = p_sprint then
            raise exception 'Carry unfinished work into a planned sprint, or back to the backlog';
        end if;
    end if;

    select jsonb_build_object(
               'committed',   cardinality(v_sprint.committed_ids),
               'added',       count(*) filter (where not (i.id = any (v_sprint.committed_ids))),
               'total',       count(*),
               'done',        count(*) filter (where i.status = 'verified' or (i.status = 'closed' and i.resolution = 'done')),
               'dropped',     count(*) filter (where i.status = 'closed' and i.resolution <> 'done'),
               'live',        count(*) filter (where i.status = 'live'),
               'merged',      count(*) filter (where i.status = 'merged'),
               'points',      coalesce(sum(public.tracker_effort_points(i.effort)), 0),
               'points_done', coalesce(sum(public.tracker_effort_points(i.effort))
                                  filter (where i.status = 'verified' or (i.status = 'closed' and i.resolution = 'done')), 0),
               'unsized',     count(*) filter (where i.effort is null)
           ),
           coalesce(array_agg(i.id) filter (where i.status not in ('verified', 'closed')), '{}')
      into v_summary, v_carried
      from public.tracker_issues i
     where i.sprint_id = p_sprint;

    update public.tracker_issues set sprint_id = p_carry_to where id = any (v_carried);

    update public.tracker_sprints
       set status = 'completed',
           completed_at = now(),
           summary = v_summary || jsonb_build_object(
               'carried', cardinality(v_carried),
               'carried_ids', to_jsonb(v_carried),
               'carried_to', p_carry_to,
               'carried_to_name', v_target.name)
     where id = p_sprint
     returning * into v_sprint;
    return v_sprint;
end;
$$;

-- Slack #development hears a sprint start and finish (tracker-slack).
create or replace function public._tracker_sprint_slack_notify()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, vault
as $$
begin
    if coalesce(current_setting('tracker.slack', true), '') = 'off'
       or new.status is not distinct from old.status
       or new.status not in ('active', 'completed') then
        return null;
    end if;

    perform net.http_post(
        url := 'https://wjvvujnicwkruaeibttt.supabase.co/functions/v1/tracker-slack',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-webhook-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'db_webhook_secret')
        ),
        body := jsonb_build_object(
            'kind', 'sprint',
            'sprint', jsonb_build_object(
                'id', new.id, 'number', new.number, 'name', new.name, 'goal', new.goal,
                'starts_on', new.starts_on, 'ends_on', new.ends_on, 'status', new.status, 'summary', new.summary
            ),
            -- What's in it now (on start: the commitment), most urgent first.
            'issues', coalesce((
                select jsonb_agg(jsonb_build_object('number', i.number, 'title', i.title, 'priority', i.priority,
                                                    'effort', i.effort, 'status', i.status)
                                 order by i.priority, i.number)
                  from public.tracker_issues i where i.sprint_id = new.id), '[]'::jsonb),
            'actor', (select coalesce(p.display_name, p.username) from public.profiles p where p.id = auth.uid())
        ),
        timeout_milliseconds := 5000
    );
    return null;
exception when others then
    raise warning '[_tracker_sprint_slack_notify] %', sqlerrm;
    return null;
end;
$$;

drop trigger if exists tracker_sprints_slack on public.tracker_sprints;
create trigger tracker_sprints_slack after update on public.tracker_sprints
    for each row execute function public._tracker_sprint_slack_notify();

alter table public.tracker_sprints enable row level security;

drop policy if exists "Admins manage tracker sprints" on public.tracker_sprints;
create policy "Admins manage tracker sprints" on public.tracker_sprints
    for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
