-- Tracker: POWR's own issue board in the admin panel (/admin/tracker).
--
-- Built around how work actually reaches people here, not around Jira's
-- defaults: every issue sits somewhere in the ecosystem (surface → area →
-- feature, the list lives in landing-page/src/pages/admin/tracker/taxonomy.js),
-- carries a ship plan (OTA, EAS build, migration, function deploy, flag…), and
-- isn't finished at "merged" or even "live": it's finished when it's VERIFIED
-- on a device, in the field or in the data.
--
-- Admin-only throughout. Claude sessions read and write it with the service
-- role (supabase db query --linked), which is why the history trigger accepts
-- a null actor and shows it as "System".

create table if not exists public.tracker_issues (
    id uuid primary key default gen_random_uuid(),
    -- POWR-<number> on screen.
    number bigint generated by default as identity unique,
    title text not null check (length(btrim(title)) between 1 and 200),
    description text not null default '' check (length(description) <= 20000),
    type text not null default 'bug'
        check (type in ('bug', 'feature', 'improvement', 'task', 'incident', 'debt', 'investigation')),
    -- triage → backlog → next → doing → review (PR open) → merged (on main,
    -- nobody has it) → live (shipped, unproven) → verified. closed = out of
    -- the flow with a resolution.
    status text not null default 'triage'
        check (status in ('triage', 'backlog', 'next', 'doing', 'review', 'merged', 'live', 'verified', 'closed')),
    resolution text check (resolution in ('done', 'wont_do', 'duplicate', 'cant_repro')),
    -- 0 = drop everything (points/money wrong, crash loop, data exposed) … 3 = someday.
    priority smallint not null default 2 check (priority between 0 and 3),

    surface text not null check (length(surface) between 1 and 40),
    area text check (length(area) <= 40),
    feature text check (length(feature) <= 80),
    platforms text[] not null default '{}' check (platforms <@ array['ios', 'android', 'web']),
    app_version text check (length(app_version) <= 40),
    labels text[] not null default '{}',
    -- What's at stake if it's wrong: points_money, privacy, security, stability,
    -- gyms_partners (they can see it), store_policy, legal.
    risks text[] not null default '{}',
    users_affected integer check (users_affected >= 0),
    effort text check (effort in ('xs', 's', 'm', 'l', 'xl')),

    assignee_id uuid references auth.users(id) on delete set null,
    waiting_on text check (waiting_on in
        ('jamie', 'team', 'gym', 'partner', 'member', 'apple', 'google', 'third_party', 'native_build', 'data')),
    waiting_note text check (length(waiting_note) <= 500),
    -- "Next OTA", "1.6.1 build", "Before ONE LDN 10-24" — free text with suggestions.
    target text check (length(target) <= 80),
    due_date date,

    -- Where the evidence and the work are.
    pr_numbers integer[] not null default '{}',
    links jsonb not null default '[]' check (jsonb_typeof(links) = 'array'),
    user_ids uuid[] not null default '{}',
    partner_id uuid references public.partners(id) on delete set null,
    event_id uuid references public.live_events(id) on delete set null,
    support_ticket_id uuid references public.support_tickets(id) on delete set null,

    -- [{ id, kind, target, done, done_at }] — kind: ota, native, store, web,
    -- function, migration, config, cron, backfill, comms.
    ship_steps jsonb not null default '[]' check (jsonb_typeof(ship_steps) = 'array'),
    -- [{ id, text, done }]
    checklist jsonb not null default '[]' check (jsonb_typeof(checklist) = 'array'),
    verify_how text check (length(verify_how) <= 2000),
    verified_note text check (length(verified_note) <= 2000),

    -- admin (typed here), support (escalated ticket), claude (filed by a session).
    source text not null default 'admin' check (source in ('admin', 'support', 'claude')),
    created_by uuid default auth.uid() references auth.users(id) on delete set null,
    updated_by uuid default auth.uid() references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    verified_at timestamptz,
    closed_at timestamptz
);

create index if not exists tracker_issues_status_idx on public.tracker_issues (status, priority, updated_at desc);
create index if not exists tracker_issues_place_idx on public.tracker_issues (surface, area);
create index if not exists tracker_issues_assignee_idx on public.tracker_issues (assignee_id) where assignee_id is not null;
create index if not exists tracker_issues_ticket_idx on public.tracker_issues (support_ticket_id) where support_ticket_id is not null;
create index if not exists tracker_issues_users_idx on public.tracker_issues using gin (user_ids);

create table if not exists public.tracker_comments (
    id uuid primary key default gen_random_uuid(),
    issue_id uuid not null references public.tracker_issues(id) on delete cascade,
    body text not null check (length(btrim(body)) between 1 and 10000),
    author_id uuid default auth.uid() references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    edited_at timestamptz
);

create index if not exists tracker_comments_issue_idx on public.tracker_comments (issue_id, created_at);

-- Append-only: written by the trigger below, never edited.
create table if not exists public.tracker_activity (
    id bigint generated always as identity primary key,
    issue_id uuid not null references public.tracker_issues(id) on delete cascade,
    actor_id uuid references auth.users(id) on delete set null,
    field text not null,
    old_value text,
    new_value text,
    created_at timestamptz not null default now()
);

create index if not exists tracker_activity_issue_idx on public.tracker_activity (issue_id, created_at);

create table if not exists public.tracker_relations (
    from_id uuid not null references public.tracker_issues(id) on delete cascade,
    to_id uuid not null references public.tracker_issues(id) on delete cascade,
    -- from blocks to / from relates to to / from duplicates to
    kind text not null check (kind in ('blocks', 'relates', 'duplicates')),
    created_by uuid default auth.uid() references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    primary key (from_id, to_id, kind),
    check (from_id <> to_id)
);

create index if not exists tracker_relations_to_idx on public.tracker_relations (to_id);

-- Stamp who and when, and the moments the board reports on.
create or replace function public.tracker_issues_touch()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at := now();
    new.updated_by := coalesce(auth.uid(), new.updated_by);
    if new.status = 'verified' and old.status is distinct from 'verified' then
        new.verified_at := now();
    end if;
    if new.status = 'closed' and old.status is distinct from 'closed' then
        new.closed_at := now();
        new.resolution := coalesce(new.resolution, 'done');
    elsif new.status <> 'closed' then
        new.closed_at := null;
        new.resolution := null;
    end if;
    return new;
end;
$$;

drop trigger if exists tracker_issues_touch on public.tracker_issues;
create trigger tracker_issues_touch before update on public.tracker_issues
    for each row execute function public.tracker_issues_touch();

-- History: one row per field that changed. Ship steps and the checklist log
-- their progress ("2/4"), not the JSON.
create or replace function public.tracker_issues_history()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    actor uuid := coalesce(auth.uid(), new.updated_by);
    steps_old text;
    steps_new text;
begin
    if tg_op = 'INSERT' then
        insert into public.tracker_activity (issue_id, actor_id, field, new_value)
        values (new.id, coalesce(auth.uid(), new.created_by), 'created', new.status);
        return new;
    end if;

    if new.status is distinct from old.status then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'status', old.status, new.status);
    end if;
    if new.priority is distinct from old.priority then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'priority', old.priority::text, new.priority::text);
    end if;
    if new.assignee_id is distinct from old.assignee_id then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'assignee', old.assignee_id::text, new.assignee_id::text);
    end if;
    if new.type is distinct from old.type then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'type', old.type, new.type);
    end if;
    if (new.surface, new.area, new.feature) is distinct from (old.surface, old.area, old.feature) then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'place',
                concat_ws('/', old.surface, old.area, old.feature),
                concat_ws('/', new.surface, new.area, new.feature));
    end if;
    if new.waiting_on is distinct from old.waiting_on then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'waiting_on', old.waiting_on, new.waiting_on);
    end if;
    if new.title is distinct from old.title then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'title', old.title, new.title);
    end if;
    if new.pr_numbers is distinct from old.pr_numbers then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'prs', array_to_string(old.pr_numbers, ','), array_to_string(new.pr_numbers, ','));
    end if;
    steps_old := (select count(*) filter (where (s->>'done')::boolean) || '/' || count(*) from jsonb_array_elements(old.ship_steps) s);
    steps_new := (select count(*) filter (where (s->>'done')::boolean) || '/' || count(*) from jsonb_array_elements(new.ship_steps) s);
    if steps_new is distinct from steps_old then
        insert into public.tracker_activity (issue_id, actor_id, field, old_value, new_value)
        values (new.id, actor, 'ship', steps_old, steps_new);
    end if;
    return new;
end;
$$;

drop trigger if exists tracker_issues_history on public.tracker_issues;
create trigger tracker_issues_history after insert or update on public.tracker_issues
    for each row execute function public.tracker_issues_history();

alter table public.tracker_issues enable row level security;
alter table public.tracker_comments enable row level security;
alter table public.tracker_activity enable row level security;
alter table public.tracker_relations enable row level security;

drop policy if exists "Admins manage tracker issues" on public.tracker_issues;
create policy "Admins manage tracker issues" on public.tracker_issues
    for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Admins manage tracker comments" on public.tracker_comments;
create policy "Admins manage tracker comments" on public.tracker_comments
    for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Admins read tracker activity" on public.tracker_activity;
create policy "Admins read tracker activity" on public.tracker_activity
    for select to authenticated using ((select public.is_admin()));

drop policy if exists "Admins add tracker activity" on public.tracker_activity;
create policy "Admins add tracker activity" on public.tracker_activity
    for insert to authenticated with check ((select public.is_admin()));

drop policy if exists "Admins manage tracker relations" on public.tracker_relations;
create policy "Admins manage tracker relations" on public.tracker_relations
    for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
